// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Таблица с базовой информацией о продуктах и их пищевой ценности (данные указаны на 100 г продукта)
type Food struct {
	ID int32
	// Название продукта
	ProductName string
	// Калорийность (ккал на 100 г)
	Calories int32
	// Жиры (г на 100 г)
	Fats pgtype.Numeric
	// Белки (г на 100 г)
	Proteins pgtype.Numeric
	// Углеводы (г на 100 г)
	Carbohydrates pgtype.Numeric
	Fiber         pgtype.Numeric
	Water         pgtype.Numeric
	VitaminA      pgtype.Numeric
	BetaCarotene  pgtype.Numeric
	AlphaCarotene pgtype.Numeric
	VitaminD      pgtype.Numeric
	VitaminD3     pgtype.Numeric
	VitaminE      pgtype.Numeric
	VitaminK      pgtype.Numeric
	VitaminC      pgtype.Numeric
	VitaminB1     pgtype.Numeric
	VitaminB2     pgtype.Numeric
	VitaminB3     pgtype.Numeric
	VitaminB4     pgtype.Numeric
	VitaminB5     pgtype.Numeric
	VitaminB6     pgtype.Numeric
	VitaminB9     pgtype.Numeric
	VitaminB12    pgtype.Numeric
	Calcium       pgtype.Numeric
	Iron          pgtype.Numeric
	Magnesium     pgtype.Numeric
	Phosphorus    pgtype.Numeric
	Potassium     pgtype.Numeric
	Sodium        pgtype.Numeric
	Zinc          pgtype.Numeric
	Copper        pgtype.Numeric
	Manganese     pgtype.Numeric
	Selenium      pgtype.Numeric
	Fluorine      pgtype.Numeric
	// Дата добавления продукта
	CreatedAt pgtype.Timestamp
}
